### ISSUE TITLE
Some tests fail on PowerPC: [ FAIL 3 | WARN 0 | SKIP 4 | PASS 16 ]

### ISSUE THREAD

**Issue by barracuda156** [prajwalkpatil/VedicDateTime#13] opened 2023-05-08 11:18 UTC
```
R version 4.3.0 (2023-04-21) -- "Already Tomorrow"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: powerpc-apple-darwin10.8.0 (32-bit)

> # This file is part of the standard setup for testthat.
> # It is recommended that you do not modify it.
> #
> # Where should you do additional test configuration?
> # Learn more about the roles of various files in:
> # * https://r-pkgs.org/tests.html
> # * https://testthat.r-lib.org/reference/test_package.html#special-files
> 
> library(testthat)
> library(VedicDateTime)
> 
> test_check("VedicDateTime")
[ FAIL 3 | WARN 0 | SKIP 4 | PASS 16 ]

══ Skipped tests ═══════════════════════════════════════════════════════════════
• Old swephR version (4)

══ Failed tests ════════════════════════════════════════════════════════════════
── Failure ('test_nakshatra.R:8:3'): Check positive testcase ───────────────────
nakshatra(vd$jd, vd$place) (`actual`) not equal to c(25, 24, 24, 1) (`expected`).

  `actual`: 25 24 24 2
`expected`: 25 24 24 1
── Failure ('test_tithi.R:8:3'): Check positive testcase ───────────────────────
tithi(vd$jd, vd$place) (`actual`) not equal to c(20, 20, 55, 35) (`expected`).

  `actual`: 20 20 55 36
`expected`: 20 20 55 35
── Failure ('test_yoga.R:8:3'): Check positive testcase ────────────────────────
yoga(vd$jd, vd$place) (`actual`) not equal to c(5, 27, 26, 12) (`expected`).

  `actual`: 5 27 26 13
`expected`: 5 27 26 12

[ FAIL 3 | WARN 0 | SKIP 4 | PASS 16 ]
Error: Test failures
Execution halted
```

**Comment by prajwalkpatil** [comment] 2023-07-18 17:49
The issue is fixed in the version 0.1.7 of the package.
CRAN - [https://cran.r-project.org/package=VedicDateTime](https://cran.r-project.org/package=VedicDateTime)

Thank you.

**Closed as completed by prajwalkpatil** 2023-07-18 17:49 UTC

**Comment by barracuda156** [comment] 2023-07-18 18:06
Thank you!

**Comment by barracuda156** [comment] 2023-07-18 18:48
@prajwalkpatil I ran tests now, and unfortunately failures are still there:
```
--->  Extracting VedicDateTime_0.1.7.tar.gz
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-VedicDateTime/R-VedicDateTime/work" && /usr/bin/gzip -dc '/opt/local/var/macports/distfiles/R-VedicDateTime/VedicDateTime_0.1.7.tar.gz' | /usr/bin/gnutar --no-same-owner -xf - 
--->  Configuring R-VedicDateTime
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-VedicDateTime/R-VedicDateTime/work/VedicDateTime" && /opt/local/bin/R CMD build . --no-manual --no-build-vignettes 
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘VedicDateTime’:
* checking DESCRIPTION meta-information ... OK
* checking vignette meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘VedicDateTime_0.1.7.tar.gz’

--->  Building R-VedicDateTime
--->  Testing R-VedicDateTime
* using log directory ‘/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-VedicDateTime/R-VedicDateTime/work/VedicDateTime/VedicDateTime.Rcheck’
* using R version 4.3.1 (2023-06-16)
* using platform: powerpc-apple-darwin10.0.0d2 (32-bit)
* R was compiled by
    gcc-mp-12 (MacPorts gcc12 12.3.0_0) 12.3.0
    GNU Fortran (MacPorts gcc12 12.3.0_0) 12.3.0
* running under: OS X Snow Leopard 10.6
* using session charset: UTF-8
* checking for file ‘VedicDateTime/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘VedicDateTime’ version ‘0.1.7’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘VedicDateTime’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘spelling.R’
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  `expected`: 20 20 55 37
  ── Failure ('test_yoga.R:7:3'): Check positive testcase ────────────────────────
  yoga(vd$jd, vd$place) (`actual`) not equal to c(5, 27, 26, 14) (`expected`).
  
    `actual`: 5 27 26 12
  `expected`: 5 27 26 14
  ── Failure ('test_yoga.R:10:3'): Check positive testcase ───────────────────────
  yoga(vd$jd, vd$place) (`actual`) not equal to c(5, 27, 26, 14) (`expected`).
  
    `actual`: 5 27 26 12
  `expected`: 5 27 26 14
  
  [ FAIL 6 | WARN 0 | SKIP 0 | PASS 17 ]
  Error: Test failures
  Execution halted
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘VedicDateTime.Rmd’ using ‘UTF-8’... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE
```
```
R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: powerpc-apple-darwin10.0.0d2 (32-bit)

> # This file is part of the standard setup for testthat.
> # It is recommended that you do not modify it.
> #
> # Where should you do additional test configuration?
> # Learn more about the roles of various files in:
> # * https://r-pkgs.org/tests.html
> # * https://testthat.r-lib.org/reference/test_package.html#special-files
> 
> library(testthat)
> library(VedicDateTime)
> 
> test_check("VedicDateTime")
[ FAIL 6 | WARN 0 | SKIP 0 | PASS 17 ]

══ Failed tests ════════════════════════════════════════════════════════════════
── Failure ('test_nakshatra.R:7:3'): Check positive testcase ───────────────────
nakshatra(vd$jd, vd$place) (`actual`) not equal to c(25, 24, 24, 3) (`expected`).

  `actual`: 25 24 24 1
`expected`: 25 24 24 3
── Failure ('test_nakshatra.R:10:3'): Check positive testcase ──────────────────
nakshatra(vd$jd, vd$place) (`actual`) not equal to c(25, 24, 24, 3) (`expected`).

  `actual`: 25 24 24 1
`expected`: 25 24 24 3
── Failure ('test_tithi.R:7:3'): Check positive testcase ───────────────────────
tithi(vd$jd, vd$place) (`actual`) not equal to c(20, 20, 55, 37) (`expected`).

  `actual`: 20 20 55 35
`expected`: 20 20 55 37
── Failure ('test_tithi.R:10:3'): Check positive testcase ──────────────────────
tithi(vd$jd, vd$place) (`actual`) not equal to c(20, 20, 55, 37) (`expected`).

  `actual`: 20 20 55 35
`expected`: 20 20 55 37
── Failure ('test_yoga.R:7:3'): Check positive testcase ────────────────────────
yoga(vd$jd, vd$place) (`actual`) not equal to c(5, 27, 26, 14) (`expected`).

  `actual`: 5 27 26 12
`expected`: 5 27 26 14
── Failure ('test_yoga.R:10:3'): Check positive testcase ───────────────────────
yoga(vd$jd, vd$place) (`actual`) not equal to c(5, 27, 26, 14) (`expected`).

  `actual`: 5 27 26 12
`expected`: 5 27 26 14

[ FAIL 6 | WARN 0 | SKIP 0 | PASS 17 ]
Error: Test failures
Execution halted
```

**Comment by prajwalkpatil** [comment] 2023-07-18 18:51
Ok @barracuda156 we will take a look at it.

Thank you.
